spring:
  zipkin:
    base-url: http://localhost:9411
  sleuth:
    sampler:
      probability: 1.0
  application:
    name: notification-service
  kafka:
    bootstrap-servers: localhost:9092
server:
  port: 0

eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://${EUREKA_USERNAME:eureka}:${EUREKA_PASSWORD:password}@${eureka.instance.hostname}:8761/eureka/
