---
version: '3.9'

services:
  mongo:
    container_name: mongo
    image: mongo:4.4
    restart: always
    ports:
      - "27017:27017"
    expose:
      - "27017"
    volumes:
      - ./.data/mongo-data:/data/db