---
version: '3.9'

services:
  mongo:
    container_name: mongo
    image: mongo:4.4
    restart: always
    ports:
      - "27017:27017"
    expose:
      - "27017"
    volumes:
      - ./.data/mongo:/data/db

  mysql-order-service:
    container_name: mysql-order-service
    image: mysql:8
    env_file:
      - .env
    environment:
      MYSQL_DATABASE: 'order_service'
    ports:
      - "3396:3306"
    volumes:
      - ./.data/mysql-order-service:/var/lib/mysql
      - ./.conf/mysql/conf.d:/etc/mysql/conf.d
    restart: unless-stopped

  mysql-inventory-service:
    container_name: mysql-inventory-service
    image: mysql:8
    env_file:
      - .env
    environment:
      MYSQL_DATABASE: 'inventory_service'
    ports:
      - "3397:3306"
    volumes:
      - ./.data/mysql-inventory-service:/var/lib/mysql
      - ./.conf/mysql/conf.d:/etc/mysql/conf.d
    restart: unless-stopped

  mysql-keycloak:
    container_name: mysql-keycloak
    image: mysql:8
    env_file:
      - .env
    volumes:
      - ./.data/mysql-keycloak:/var/lib/mysql
    environment:
      MYSQL_DATABASE: keycloak

  keycloak:
    container_name: keycloak
    image: quay.io/keycloak/keycloak:18.0.0
    command: [ "start-dev", "--import-realm" ]
    env_file:
      - .env
    environment:
      DB_VENDOR: MYSQL
      DB_ADDR: mysql
      DB_DATABASE: keycloak
      DB_USER: ${MYSQL_USER}
      DB_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "8181:8080"
    #volumes:
    #  - ./.conf/realms/:/opt/keycloak/data/import/
    depends_on:
      - mysql-keycloak