spring:
  application:
    name: product-service
  data:
    mongodb:
      host: mongo
      port: 27017
      database: product-service
  zipkin:
    base-url: http://zipkin:9411
  sleuth:
    sampler:
      probability: 1.0
server:
  port: 8080
eureka:
  instance:
    hostname: discovery-server
  client:
    service-url:
      defaultZone: http://${EUREKA_USERNAME:eureka}:${EUREKA_PASSWORD:password}@${eureka.instance.hostname}:8761/eureka/